export const FORM_INPUT_GET_LIST_ERR = 'FORM_INPUT_GET_LIST_ERR';
export const FORM_INPUT_GET_LIST_REQ = 'FORM_INPUT_GET_LIST_REQ';
export const FORM_INPUT_GET_LIST_RES = 'FORM_INPUT_GET_LIST_RES';

export const FORM_OUTPUT_SUMMIT_ERR = 'FORM_OUTPUT_SUMMIT_ERR';
export const FORM_OUTPUT_SUMMIT_REQ = 'FORM_OUTPUT_SUMMIT_REQ';
export const FORM_OUTPUT_SUMMIT_RES = 'FORM_OUTPUT_SUMMIT_RES';
