export const FORM_MODAL_INITIALIZE = 'FORM_MODAL_INITIALIZE'; // 초기화
// submit
export const FORM_MODAL_SUBMIT_PROGRESSED = 'FORM_MODAL_SUBMIT_PROGRESSED'; // 이전.이후 진행
export const FORM_MODAL_SUBMIT_COMPLETED = 'FORM_MODAL_SUBMIT_COMPLETED'; // 최종 제출
export const FORM_MODAL_SUBMIT_ERROR = 'FORM_MODAL_SUBMIT_ERROR'; // 에러

// checkbox
export const FORM_MODAL_CHECKBOX_CHECKED = 'FORM_MODAL_CHECKBOX_CHECKED'; // 클릭처리
// ratio
export const FORM_MODAL_RADIO_CHECKED = 'FORM_MODAL_RADIO_CHECKED'; // 클릭처리
// select
export const FORM_MODAL_SELECTBOX_SELECTED = 'FORM_MODAL_SELECTBOX_SELECTED'; // 선택처리
// text input
export const FORM_MODAL_TEXT_INPUT = 'FORM_MODAL_TEXT_INPUT'; // 입력처리